require:
  - rubocop-performance
  - rubocop-rails
  - rubocop-rspec

AllCops:
  NewCops: enable
  SuggestExtensions: false
  Exclude:
    - 'db/**/*'
    - 'script/**/*'
    - 'bin/**/*'
    - 'spec/**/*'
    - 'Gemfile'
    - 'Gemfile.lock'
    - 'config/**/*'

Layout/LineLength:
  Max: 100
  Exclude:
    - 'config/initializers/devise.rb'

Metrics/BlockLength:
  Enabled: false

Metrics/ClassLength:
  Exclude:
    - app/services/*

Metrics/MethodLength:
  Enabled: false

Lint/AmbiguousBlockAssociation:
  Exclude:
    - spec/**/*

Style/Documentation:
  Enabled: false

Rails/HasAndBelongsToMany:
  Enabled: false

RSpec/ExampleLength:
  Enabled: false

RSpec/MultipleExpectations:
  Enabled: false

RSpec/ImplicitSubject:
  Enabled: false
